### ISSUE TITLE
Crash with new Railcraft

### ISSUE THREAD

**Issue by rrusciguy** [TheCricket/Chisel-2#203] opened 2015-02-05 01:40 UTC
With the new build of Railcraft CJ has released (currently only to patrons) the following exception is thrown when registering abyssal blocks

EDIT: RC version is 9.4.0.3, chisel is latest release

http://pastebin.com/885s0myA

**Comment by tterrag1098** [comment] 2015-02-05 02:06
We will fix support when the version is officially released. For now, disable the railcraft feature.

**Comment by TheCricket** [comment] 2015-02-05 02:11
Thanks for the heads up but if it's only to patrons nothing I can do about that atm

**Comment by tterrag1098** [comment] 2015-02-05 03:34
It's odd though, he must be changing how blocks are registered but that'll break worlds if he's not careful.

**Comment by Syer10** [comment] 2015-02-07 03:33
New railcraft released here http://minecraft.curseforge.com/mc-mods/51195-railcraft/files/2226556 here is the same crash but with the released version http://pastebin.com/ffWRmwJS

**Comment by chloeprince** [comment] 2015-02-07 08:02
Oh good... Its not just me - HALP!

Running the latest Railcraft 9.5.0.0 and getting the same crash as everyone above.

**Comment by Sailren** [comment] 2015-02-07 09:50
me 2

**Comment by Staegrin** [comment] 2015-02-07 12:16
After updating to Railcraft_1.7.10-9.5.0.0. The game would start loading and then crash to desktop. I've narrowed down the cause to the chisel mod  (Chisel2-2.3.4.30). Without this mod or downgrading to version (Railcraft_1.7.10-9.4.0.0) there is no crash.
crashlogs:
http://pastebin.com/gzNLrZPk
http://pastebin.com/2rv1ZDAW

cross-post from Railcraft. Usually I go to github of mod that updated first.

**Comment by Roversword** [comment] 2015-02-07 14:58
Same issue and same error message as rrusciguy (Railcraft 9.5.0.0, Chisel 2.3.5, both from curse.com).
If there is anything I can help in terms of error messages or testing or providing more information, let me know.

**Comment by erkro1** [comment] 2015-02-07 16:38
Please release new Chisel version asap, everyone with Chisel and new Railcraft has this crash.

**Comment by tterrag1098** [comment] 2015-02-07 16:59
Either disable the railcraft feature as mentioned above, or use the nightly here: http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/46/

MAKE A BACKUP BEFORE USING NIGHTLIES

**Comment by jermangarc** [comment] 2015-02-08 00:58
Did you guys remove the cool chests on the nightly version? When I loaded my test world it stated that there were missing blocks (a bunch of chisel chests).

**Comment by tterrag1098** [comment] 2015-02-08 03:32
Redid them. Old ones will vanish but they never worked anyhow.

**Comment by Pilad** [comment] 2015-02-11 17:35
Crash cauldron forge 1240 server 

[20:33:13] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class Reflector
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:163) ~[b.class:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:55) ~[b.class:?]
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:442) ~[b.class:?]
	at net.minecraft.world.World.<init>(World.java:189) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[20:33:13] [Server thread/INFO]: Applying holder lookups
[20:33:13] [Server thread/WARN]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[20:33:13] [Server thread/WARN]: Unable to lookup chisel:arcane for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.arcane. Is there something wrong with the registry?
[20:33:13] [Server thread/WARN]: Unable to lookup chisel:thaumium for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.thaumium. Is there something wrong with the registry?
[20:33:13] [Server thread/WARN]: Unable to lookup chisel:tallow for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.tallow. Is there something wrong with the registry?
[20:33:13] [Server thread/WARN]: Unable to lookup chisel:bloodRune for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[20:33:13] [Server thread/WARN]: Unable to lookup chisel:bloodBrick for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[20:33:13] [Server thread/INFO]: Holder lookups applied
[20:33:13] [pool-4-thread-1/INFO]: ServerChannelRegister: Dimensional Trasciever data saved to /1/./world/enderio/dimensionalTransceiver.json
[20:33:13] [Server thread/INFO]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by Pilad** [comment] 2015-02-11 17:36
I use dev build Chisel2_DEV-2.3.5.bc8e2a5

**Comment by Pilad** [comment] 2015-02-11 17:47
If use stable version chisel and Railcraft 9.4.0.0 .:

[20:45:08 ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class Reflector
        at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:163) ~[b.class:?]
        at net.minecraft.crash.CrashReport.<init>(CrashReport.java:55) ~[b.class:?]
        at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:442) ~[b.class:?]
        at net.minecraft.world.World.<init>(World.java:189) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[20:45:08 INFO]: Applying holder lookups
[20:45:08 WARN]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[20:45:08 WARN]: Unable to lookup chisel:arcane for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.arcane. Is there something wrong with the registry?
[20:45:08 WARN]: Unable to lookup chisel:thaumium for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.thaumium. Is there something wrong with the registry?
[20:45:08 WARN]: Unable to lookup chisel:tallow for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.tallow. Is there something wrong with the registry?
[20:45:08 WARN]: Unable to lookup chisel:bloodRune for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[20:45:08 WARN]: Unable to lookup chisel:bloodBrick for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[20:45:08 INFO]: Holder lookups applied
[20:45:08 INFO]: ServerChannelRegister: Dimensional Trasciever data saved to /1/./world/enderio/dimensionalTransceiver.json
[20:45:08 INFO]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by CptSpaceToaster** [comment] 2015-02-11 17:48
@Pilad, You can try last evening's update (It probably won't help anything though) http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/50/

Also, what version of railcraft are you using?

**Comment by Pilad** [comment] 2015-02-11 17:56
Hm... I delete chisel... :

[20:54:06 ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class Reflector
        at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:163) ~[b.class:?]
        at net.minecraft.crash.CrashReport.<init>(CrashReport.java:55) ~[b.class:?]
        at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:442) ~[b.class:?]
        at net.minecraft.world.World.<init>(World.java:189) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[20:54:06 INFO]: Applying holder lookups
[20:54:06 INFO]: Holder lookups applied
[20:54:06 INFO]: ServerChannelRegister: Dimensional Trasciever data saved to /1/./world/enderio/dimensionalTransceiver.json
[20:54:06 INFO]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
 Not understand (((((

**Comment by Pilad** [comment] 2015-02-11 18:14
Ooo...I not delete optifine on server... 
And error : java.lang.NoClassDefFoundError: Could not initialize class Reflector
Sorry....

**Comment by CptSpaceToaster** [comment] 2015-02-11 19:27
@PIlad, Can you update Railcraft to 9.5.X?
RC 9.4.0 is a bit old.

9.5.X should work with the latest dev build of chisel.

**Comment by tterrag1098** [comment] 2015-02-11 19:49
9.4.x should still work though, I coded it to work with both

**Comment by CptSpaceToaster** [comment] 2015-02-11 20:16
True... @Pilad did not indicate Chisel-2 is still failing...
I bet his issue with Chisel-2 fixed now that he fixed his other issue with optifine on the server...

**Comment by Cronosus** [comment] 2015-02-13 18:41
same problem, crash with railcraft 9.5.0.0 and chisel 2.3.5
http://pastebin.com/c63wWgsr

**Comment by tterrag1098** [comment] 2015-02-13 19:10
@Cronosus why post it again? The fix has been posted above.

**Comment by CptSpaceToaster** [comment] 2015-02-13 19:40
For anyone about to post another useless crash/message/reminder/whatever, "Code Complete" means that we've fixed the bug in our dev-branch.  

The fix will make it out in our next release.

Please be patient, and you'll get your fix soon.

**Closed** 2015-02-15 02:28 UTC
Labels: bug, code complete
