### ISSUE TITLE
Crash when using Chisel and BiblioCraft's inventories

### ISSUE THREAD

**Issue by xJon** [TheCricket/Chisel-2#188] opened 2015-01-29 15:38 UTC
While holding a chisel and right clicking most of the inventories, they just open and ignores the chisel function. While holding a chisel and right clicking any inventory of the BiblioCraft mod, it puts the chisel in the inventory but also opens the Chisel GUI. If you try to use this GUI your game crashing.
Crash report: http://pastebin.com/SC6GBAxz

**Comment by TheCricket** [comment] 2015-01-29 18:48
duplicate of #119

**Closed by TheCricket** 2015-01-29 18:48 UTC
