### ISSUE TITLE
Feature Request: Chiseled Stair variants 

### ISSUE THREAD

**Issue by XBlackLeopardX** [TheCricket/Chisel-2#273] opened 2015-03-24 05:05 UTC
I've got no idea if this has been mentioned before it would surprise me if it hasnt but I believe it would be really useful and nice if there where variants of the stairs for all the blocks in the mod

The only other way is to also install the carpenter block mod which I know in large amounts can cause lag idk to what extend but I know it can cause frame rate drop

**Comment by warlordjones** [comment] 2015-04-05 15:52
This is a dupe of #69. Closing newer one, as is my personal policy.

**Closed by warlordjones** 2015-04-05 15:52 UTC
Labels: enhancement
