### ISSUE TITLE
Only diorite generates in new worlds...

### ISSUE THREAD

**Issue by Abraxas0090** [TheCricket/Chisel-2#152] opened 2015-01-17 05:41 UTC
i can only find diorite anytime i start a new world using the last jenkins build. no marble or limestone anywhere but i see they exist in nei. i was using a ton of mods and thought it was some kind of conflict so i tried using just forge 10.13.2.1286 and the last dev build of chisel and still only see diorite. is this intentional?

**Comment by erkro1** [comment] 2015-01-17 09:31
I believe this is a duplicate of this issue: https://github.com/TheCricket/Chisel-2/issues/130

**Comment by Drullkus** [comment] 2015-01-17 09:37
Yes it seems to be a dupe of #130 , closing

**Closed by Drullkus** 2015-01-17 09:37 UTC

**Comment by Abraxas0090** [comment] 2015-01-17 17:17
oh! i didn't see that or i wouldn't have made an issue. i'm sorry, i'm pretty new to this. thank you anyway!
