### ISSUE TITLE
A lot of spam In my console

### ISSUE THREAD

**Issue by crunkazcanbe** [TheCricket/Chisel-2#91] opened 2015-01-02 20:52 UTC
Dont know what it all means , but apparently this mod is conflicting with something . Log here http://pastebin.com/yWJ6zTi9

Thanx -Crunk

**Comment by TheCricket** [comment] 2015-01-02 20:53
Duplicate of #84

**Comment by crunkazcanbe** [comment] 2015-01-02 20:59
Thanx man sorry about the dup .

**Comment by TheCricket** [comment] 2015-01-04 14:55
Not a problem. I registered a block that doesnt exist accidently, thats all this means. It is harmless

**Closed** 2015-01-05 23:18 UTC
Labels: duplicate
