### ISSUE TITLE
Chisel2_DEV-2.2.2.57708f1 Crash with Twilight Forest

### ISSUE THREAD

**Issue by SJ1133** [TheCricket/Chisel-2#151] opened 2015-01-17 03:14 UTC
The game refuses to load and crashes. 
LOG : http://pastebin.com/qE28dXtK
Forge Version: 1272

**Comment by tterrag1098** [comment] 2015-01-17 03:16
Could you test without TF? It seems to be erroring while adding the TF compatability.

**Comment by SJ1133** [comment] 2015-01-17 03:22
The game seems to be loading without Thermal Foundation. But obviously it show that this mod could not be found.
On another note the dev build is been buling for 18 hours . I assume thats not normal?

**Comment by tterrag1098** [comment] 2015-01-17 03:23
Not thermal foundation, sorry, Twilight Forest.

**Comment by tterrag1098** [comment] 2015-01-17 03:27
That build should be fixed now.

**Comment by SJ1133** [comment] 2015-01-17 03:28
The game is loading with Twilight Forest Disabled. Is there a quick fix or will you have to fix it?

And thanks for the build fix.

**Comment by tterrag1098** [comment] 2015-01-17 03:30
I'll need to get the correct block names from TF to use, as evidently ours are wrong.

**Comment by SJ1133** [comment] 2015-01-17 03:34
Alight Thanks :) Will test some more when i see a new build. Thanks for all the work

**Comment by tterrag1098** [comment] 2015-01-17 03:41
Actually it appears the issue is that we didn't tell FML we need to load *after* TF. A quick fix would be renaming the chisel jar to something that is alphabetically after T, so ZChisel-2 would be fine :P

**Comment by SJ1133** [comment] 2015-01-17 03:43
Thanks for that. I thought i would have to wait to play mc D: You are awesome :+1:

**Comment by tterrag1098** [comment] 2015-01-17 03:44
Fixed via 331f40169015200bf30bbd46f37e39dd56d81863

**Closed** 2015-01-20 23:18 UTC
Labels: bug, code complete
