### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Tictim** [TheCricket/Chisel-2#225] opened 2015-02-14 08:47 UTC
https://gist.github.com/anonymous/8fe50a171a5824374c6d

**Comment by CptSpaceToaster** [comment] 2015-02-14 15:13
Duplicate of: https://github.com/TheCricket/Chisel-2/issues/203
Please don't post crash reports without any context, or attempt at solving your problem.  This should have been obvious.

**Closed by CptSpaceToaster** 2015-02-14 15:13 UTC
