### ISSUE TITLE
[Crash]: Advanced Renderer - With Chisel Marble Column Crash

### ISSUE THREAD

**Issue by Lanse505** [TheCricket/Chisel-2#212] opened 2015-02-07 22:35 UTC
One of our players on my friends Streaming server is crashing whenever he comes close to one of the streamers base and crashes due to "Adv Render - Chisel Marble Column"

Crashlog: 
http://pastebin.com/pZkXdm5a

**Comment by tterrag1098** [comment] 2015-02-08 00:39
Old bug, this has been fixed and is a duplicate of #194

**Closed by tterrag1098** 2015-02-08 00:39 UTC
