### ISSUE TITLE
Serious dupe of everything

### ISSUE THREAD

**Issue by Wise1986** [TheCricket/Chisel-2#257] opened 2015-03-04 17:49 UTC
Chisel 2.3.7 allows to dupe any block:

Steps to reproduce:
[REDACTED]

**Comment by CptSpaceToaster** [comment] 2015-03-04 17:55
Related to: https://github.com/TheCricket/Chisel-2/issues/236

**Comment by tterrag1098** [comment] 2015-03-04 18:02
This does not work for me. I reproduced exactly your steps and it does not dupe the blocks.

**Comment by tterrag1098** [comment] 2015-03-04 18:26
I've added some code to prevent this being able to happen and censored your post in case it is possible in some situation I can't reproduce.

**Comment by Wise1986** [comment] 2015-03-04 19:05
look this video to see the process in details. Found this today and then checked on my pack and reproduced this dupe:

https://www.youtube.com/watch?v=1DOx8GU2uW0&t=51

**Comment by TheCricket** [comment] 2015-03-04 19:56
We censored it for a reason. Never make a video of a dupe public

**Comment by Wise1986** [comment] 2015-03-04 19:57
its not mine, just found it on youtube

**Comment by tterrag1098** [comment] 2015-03-04 20:35
Regardless don't publicize it. This is fixed now.

**Comment by Wise1986** [comment] 2015-03-07 13:11
i have compiled latest dev version and this bug is still reproducible

**Comment by frozenLake** [comment] 2015-03-07 18:46
Erm, might need to censor your post too, @TheCricket, as it has the link.

**Comment by Drullkus** [comment] 2015-03-07 19:24
@frozenLake Done

**Comment by Wise1986** [comment] 2015-03-07 19:29
its not a way out you have to release fixed version asap, current fix doesnt work

**Comment by tterrag1098** [comment] 2015-03-07 19:45
@Wise1986 We will release the new version when it is ready and no sooner.

**Closed** 2015-03-25 01:45 UTC
Labels: bug, code complete
