### ISSUE TITLE
Placing an Iron Block in a Chisel Clientside crashes Client when on Server

### ISSUE THREAD

**Issue by MillanAireson** [TheCricket/Chisel-2#96] opened 2015-01-03 18:14 UTC
I have the client and a server running. Not sure if that makes a difference, but I wanted to call that out.

Does not appear to happen in single player, only when connected to a server.

When attempting to put an iron block in the chisel, the client crashes. when I logged back in, you can see that the iron block is in fact in the chisel, but if you attempt to open the chisel interface, the client just crashes again.   No additional mods, resource packs, or Optifine. A single block of iron crashed it. I have successfully used the chisel on cobble, stone, marble, and netherrack....

Crash Log:  http://pastebin.com/Syb277DQ

**Comment by Drullkus** [comment] 2015-01-03 18:17
What Chisel version are you using?

**Comment by CptSpaceToaster** [comment] 2015-01-03 18:22
Log appears to indicate Chisel 2.2.1:
`chisel{2.2.1} [Chisel] (Chisel 2-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available`

**Comment by MillanAireson** [comment] 2015-01-03 19:18
Someone changed the title.  It does NOT crash the server.  It crashes the client when on a server.  And one other note, this was copied from my original post of the GitHub for the mod pack I am using.  It is called, "The 1.7.10 Pack" on Technic.  The author after looking into it believes it is not on his side and a bug with Chisel.

**Comment by TheCricket** [comment] 2015-01-04 14:54
Looks like I may have used the wrong import will definitely look at this

**Comment by warlordjones** [comment] 2015-01-11 09:14
Can't reproduce, did you fix this @TheCricket ?

**Comment by tterrag1098** [comment] 2015-01-15 18:51
I think this is absolutely fixed in the dev builds, but I would like @MillanAireson to confirm.

**Comment by tterrag1098** [comment] 2015-01-21 01:06
Closing due to unresponsiveness.

**Closed** 2015-01-21 01:06 UTC
Labels: bug, question
